export const PROJECT_ICON_OPTIONS = [
  'assignment',
  'view_kanban',
  'rocket_launch',
  'design_services',
  'code',
  'campaign',
  'school',
  'home_repair_service',
  'work',
  'business_center',
  'account_tree',
  'folder',
  'inventory_2',
  'task_alt',
  'fact_check',
  'dashboard',
  'analytics',
  'query_stats',
  'calendar_month',
  'event',
  'groups',
  'person_add',
  'handshake',
  'public',
  'language',
  'travel_explore',
  'shopping_bag',
  'payments',
  'attach_money',
  'savings',
  'monitoring',
  'lightbulb',
  'psychology',
  'auto_awesome',
  'construction',
  'build',
  'engineering',
  'architecture',
  'brush',
  'palette',
  'edit_note',
  'draw',
  'article',
  'menu_book',
  'science',
  'biotech',
  'health_and_safety',
  'fitness_center',
  'restaurant',
  'local_cafe',
  'home',
  'apartment',
  'storefront',
  'support_agent',
  'bug_report',
  'security',
  'lock',
  'key',
  'cloud',
  'database',
  'dns',
  'terminal',
  'memory',
  'devices',
  'smartphone',
  'web',
  'integration_instructions',
  'api',
  'hub',
  'electric_bolt',
  'bolt',
  'flag',
  'emoji_events',
  'star',
  'favorite'
] as const;

export const PROJECT_COLOR_OPTIONS = [
  { label: 'Purple', value: '#B072FF' },
  { label: 'Blue', value: '#3EAEFF' },
  { label: 'Green', value: '#00F4B9' },
  { label: 'Orange', value: '#FFC000' },
  { label: 'Rose', value: '#FF3366' }
] as const;
